### ISSUE TITLE
Small miss used variable in bohra

### ISSUE THREAD

**Issue by abcdtree** [MDU-PHL/bohra#45]
Snakemake parameter 
 Bohra passed args.cpus to SnpDetection object self.cpus during the initial
 Then, there is a func name: set_snakemake_jobs() to double check whether the self.cpus is over the limitation:
 SnpDetection.py#L141
 def set_snakemake_jobs(self):
 	'''
        set the number of jobs to run in parallel based on the number of cpus from args
    '''
    if int(self.cpus) < int(psutil.cpu_count()):
        self.jobs =  self.cpus
    else:
        self.jobs = 1
However, in the final command line to run snakemake file, it does not use self.jobs.
if self.cluster:
    cmd = f"{self.cluster_cmd()} -s {snake_name} -d {wd} {force} {singularity_string} --latency-wait 1200"
else:
    cmd = f"snakemake {dry} -s {snake_name} {singularity_string} -j {self.cpus} -d {self.job_id} {force} --verbose 2>&1"

**Comment by kristyhoran** [comment]
Snakemake is no longer used
